version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  # Redis
  redis:
    container_name: redis-pos
    image: redis:7.0
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: {}
